# Generated by Django 4.0.5 on 2022-06-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('memoria', models.IntegerField()),
            ],
        ),
    ]
