# Generated by Django 4.0.5 on 2022-06-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apli', '0002_videocards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba1', models.CharField(max_length=10)),
                ('prueba2', models.CharField(max_length=10)),
            ],
        ),
    ]
