# Generated by Django 4.0.5 on 2022-06-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apli', '0003_prueba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='prueba1',
            new_name='cambioNombre',
        ),
    ]
