# Generated by Django 4.0.5 on 2022-06-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apli', '0004_rename_prueba1_prueba_cambionombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_juego', models.CharField(max_length=10)),
                ('tipo_de_Juego', models.CharField(max_length=10)),
                ('espacio_en_disco', models.IntegerField()),
                ('fecha_lanzamiento', models.DateField()),
            ],
        ),
    ]
